# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands:
  - msbuild
  - visualstudio
  
name: '$(BuildDefinitionName) $(MajorVersion).$(MinorVersion).$(DayOfYear)$(Rev:.r)'

variables:
  buildConfiguration: 'Release'  
  BuildPlatform: 'any cpu'
  MajorVersion: '1'
  MinorVersion: '0'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: PowerShell@2
  inputs:
    filePath: './ApplyVersionToAssemblies.ps1'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: PublishSymbols@2
  inputs:
    SearchPattern: '**/bin/**/*.pdb'
    SymbolServerType: 'TeamServices'


# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/package'
#   inputs:
#     SourceFolder: './'
#     Contents: |
#      Xamarin.Android.LiveChat.nuspec
#      Xamarin.Android.LiveChat.Android/bin/Release/Xamarin.Android.LiveChat.*
#     TargetFolder: '$(Build.ArtifactStagingDirectory)/package'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: './'
    Contents: |
     Set-PackageQuality.ps1
     ApplyVersionToAssemblies.ps1
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: Nuget-Package'
#   inputs:
#     ArtifactName: 'Nuget-Package'